cofhud.toolmenu.enabled=Activo
cofhud.toolmenu.reset=Reiniciar opciones a valores por defecto
cofhud.toolmenu.version=Versión %s
cofhud.toolmenu.features=Composición
cofhud.toolmenu.feature.health=Panel de salud activo
cofhud.toolmenu.feature.armor=Panel de armadura activo
cofhud.toolmenu.feature.armor_icon=Utilizar icono no oficial de armadura
cofhud.toolmenu.feature.armor_icon.help=¡Solo funciona si la potencia aux. está desactivada!
cofhud.toolmenu.feature.health_stack=Apilar barras de salud y armadura
cofhud.toolmenu.feature.suitpower=Panel de energía del traje activo
cofhud.toolmenu.feature.ammo=Panel de munición activo
cofhud.toolmenu.feature.ammo_clips=Mostrar recuento de cargadores de reserva
cofhud.toolmenu.feature.ammo_stack=Dividir cargador si es demasiado grande
cofhud.toolmenu.feature.damage=Activar filtro de daño
cofhud.toolmenu.feature.death=Activar pantalla de muerte
cofhud.toolmenu.feature.death_cam=Activar cámara de muerte en primera persona
cofhud.toolmenu.feature.death_simple=Simplificar menú de muerte
cofhud.toolmenu.feature.notifications=Activar notificaciones
cofhud.toolmenu.feature.pickup=Activar mensaje de recogida de objetos
cofhud.toolmenu.feature.intro=Activar introducción del mapa
cofhud.toolmenu.feature.intro_reset=Reiniciar introducción del mapa
cofhud.toolmenu.pos=Posicionamiento
cofhud.toolmenu.pos.health.x=X salud
cofhud.toolmenu.pos.health.y=Y salud
cofhud.toolmenu.pos.armor.x=X armadura
cofhud.toolmenu.pos.armor.y=Y armadura
cofhud.toolmenu.pos.suitpower.x=X energía del traje
cofhud.toolmenu.pos.suitpower.y=Y energía del traje
cofhud.toolmenu.pos.ammo.x=X munición
cofhud.toolmenu.pos.ammo.y=Y munición
cofhud.toolmenu.credits.code=Código escrito por DyaMetR
cofhud.toolmenu.credits.gamedev=Concepto y arte por Team Psykskallar

cofhud.pickup.weapon=Has obtenido %s
cofhud.pickup.item=Has recogido un/a %s
cofhud.pickup.ammo=Has recogido %i %s
cofhud.pickup.ammo_alt=Has recogido %i cargas de %s
cofhud.pickup.ammo_mag=Has recogido un cargador de %s con %i cartuchos
cofhud.pickup.ammo_box=Has recodigo una caja de %s con %i cartuchos
cofhud.pickup.ammo_pack=Has recogido un paquete de %s con %i cartuchos
