cofhud.toolmenu.enabled=Enabled
cofhud.toolmenu.reset=Reset settings to default
cofhud.toolmenu.version=Version %s
cofhud.toolmenu.features=Composition
cofhud.toolmenu.feature.health=Health panel enabled
cofhud.toolmenu.feature.armor=Armor panel enabled
cofhud.toolmenu.feature.armor_icon=Use unofficial icon for armor
cofhud.toolmenu.feature.armor_icon.help=Only works if aux. power is disabled!
cofhud.toolmenu.feature.health_stack=Stack health and armor bars
cofhud.toolmenu.feature.suitpower=Suit power panel enabled
cofhud.toolmenu.feature.ammo=Ammo panel enabled
cofhud.toolmenu.feature.ammo_clips=Show reserve ammo in clip count
cofhud.toolmenu.feature.ammo_stack=Divide clip indicator on oversize
cofhud.toolmenu.feature.damage=Enable damage overlay
cofhud.toolmenu.feature.death=Enable death screen
cofhud.toolmenu.feature.death_cam=Enable first person death camera
cofhud.toolmenu.feature.death_simple=Simplify death menu
cofhud.toolmenu.feature.notifications=Enable notifications
cofhud.toolmenu.feature.pickup=Enable item pickup dialog
cofhud.toolmenu.feature.intro=Enable map intro
cofhud.toolmenu.feature.intro_reset=Reset map intro
cofhud.toolmenu.pos=Positioning
cofhud.toolmenu.pos.health.x=Health panel X
cofhud.toolmenu.pos.health.y=Health panel Y
cofhud.toolmenu.pos.armor.x=Armor panel X
cofhud.toolmenu.pos.armor.y=Armor panel Y
cofhud.toolmenu.pos.suitpower.x=Suit power panel X
cofhud.toolmenu.pos.suitpower.y=Suit power panel Y
cofhud.toolmenu.pos.ammo.x=Ammo panel X
cofhud.toolmenu.pos.ammo.y=Ammo panel Y
cofhud.toolmenu.credits.code=Coded by DyaMetR
cofhud.toolmenu.credits.gamedev=Concept and artwork by Team Psykskallar

cofhud.pickup.weapon=You got the %s
cofhud.pickup.item=Picked up a %s
cofhud.pickup.ammo=Picked up %i %s
cofhud.pickup.ammo_alt=Picked up %i %s rounds
cofhud.pickup.ammo_mag=Picked up a %s magazine with %i rounds
cofhud.pickup.ammo_box=Picked up a box of %s with %i rounds
cofhud.pickup.ammo_pack=Picked up a package of %s with %i rounds
